name: MY FIRST WORKFLOW

on: 
    push: 
        branches: 
            - main
    
    workflow_dispatch: 
jobs:
    AWS-DEPLOYMENT:
        runs-on: ubuntu-latest

        steps:
          - name: COPY CODE FROM GITHUB
            uses: actions/checkout@v6
        
          - name: SETUP NODE
            uses: actions/setup-node@v4
            with:
                node-version: 20
                cache: npm
                
          -  name: INSTALL DEPENDENCIES
             run: npm ci
          - name: COMPILE CODE
            run: npm run build
            
          - name: RUN TEST
            run: npm test
          - name: PACKAGE COMPILED CODE
            run: |
                 mkdir compileCode
                 cp -r dist compileCode/
                 cp package.json package-lock.json compileCode/

          - name: INSTALL PROD DEPENDENCIES
            working-directory: compileCode
            run: npm ci --omit=dev

          - name: WE ARE DONE
            run: |
                echo "Error: no test specified"